# 摘要

程序可以使用异常来指示发生错误。要抛出异常，请使用 throw 语句并提供一个异常对象（一个Throwable的子类）来提供有关发生的特定的错误信息。抛出未捕获的检查异常的方法必须声明 throws ，再此抛出。

程序可以通过使用`try、catch、finally`块组合捕获异常
* try块：标识可以发生异常的代码块。
* catch块：标识一个可以处理特定类型异常的代码块，称为异常处理程序。
* finally块：标识一个确保执行的代码块，并且是封闭文件，恢复资源，以及在try块中包含的代码之后进行清理的正确位置。

try语句应该至少包含一个 catch块或finally块，并且可以具有多个catch块

异常对象的类指示抛出的异常的类型。异常对象可以包含有关错误的进一步信息，包括错误消息。使用异常链接，异常可以指向导致它的异常，这可能反过来指向导致它的异常，等等。

